// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InterViewProject.Models;

public partial class Continent
{
    public int ContinentId { get; set; }

    public string ContinentName { get; set; }

    public virtual ICollection<Country> Countries { get; set; } = new List<Country>();
}