// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InterViewProject.Models;

public partial class Country
{
    public int CountryId { get; set; }

    public string CountryName { get; set; }

    public int ContinentId { get; set; }

    public virtual ICollection<Coffee> Coffees { get; set; } = new List<Coffee>();

    public virtual Continent Continent { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}