// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InterViewProject.Models;

public partial class Photo
{
    public int PhotoId { get; set; }

    public int? ProductId { get; set; }

    public string ImagePath { get; set; }

    public virtual Product Product { get; set; }
}