// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InterViewProject.Models;

public partial class Process
{
    public int ProcessId { get; set; }

    public string ProcessName { get; set; }

    public virtual ICollection<Coffee> Coffees { get; set; } = new List<Coffee>();
}