// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InterViewProject.Models;

public partial class ProductListView
{
    public string ProductName { get; set; }

    public string CountryName { get; set; }

    public string ContinentName { get; set; }

    public string ProcessName { get; set; }

    public string RoastingName { get; set; }

    public string CategoriesName { get; set; }

    public decimal? Price { get; set; }

    public bool TakeDown { get; set; }
}