// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InterViewProject.Models;

public partial class Product
{
    public int ProductId { get; set; }

    public string ProductName { get; set; }

    public int CategoryId { get; set; }

    public int? CountryId { get; set; }

    public decimal? Price { get; set; }

    public string Description { get; set; }

    public int? Stock { get; set; }

    public int? ClickCount { get; set; }

    public bool TakeDown { get; set; }

    public double? Star { get; set; }

    public string MainPhotoPath { get; set; }

    public virtual Category Category { get; set; }

    public virtual Coffee Coffee { get; set; }

    public virtual Country Country { get; set; }
}